### ISSUE TITLE
Missing interpreter line

### ISSUE THREAD

**Issue by ghost** [Wolfant/ansible-jbossCli#5]
Hey guys!

Running my recipe:
```

  - name: Deploy eSL-AdminConsole.ear
    jbosscli:
      command: deploy /opt/files/esle/eSL-AdminConsole.ear
      cli_path: /opt/wildfly-8.2.1-node1/bin
      server: localhost:19990
      verbose: yes

  - name: Deploy eSL-ResourcesManager.ear
    jbosscli:
      command: deploy /opt/files/esle/eSL-ResourcesManager.ear
      cli_path: /opt/wildfly-8.2.1-node1/bin
      server: localhost:19990
      verbose: yes
```
I am getting this:
fatal: [192.168.11.81]: FAILED! => {"msg": "module (jbosscli) is missing interpreter line"}

Any suggestion why?
